-- Intentionally a no-op.
--
-- drizzle-kit generated this migration because 0004 was hand-written without a
-- snapshot, so it still believed "verification_token" existed and emitted a
-- rename of it. 0004 already dropped that column, added
-- "verification_token_hash", made "verification_token_expires" timezone-aware
-- and created "users_verification_token_hash_idx", so the generated statements
-- failed ("column verification_token does not exist") and blocked every later
-- migration. The file stays so its snapshot (meta/0005_snapshot.json) remains
-- the baseline drizzle-kit diffs against.
SELECT 1;
